package it.redhat.hacep.playground.rules.reward.catalog;

import it.redhat.hacep.playground.rules.model.Gameplay;

declare Gameplay
    @role( event )
    @timestamp ( instant.toEpochMilli() )
end

rule "retract test rule"
salience 10
when
    $gamePlay : Gameplay($playerId : playerId) over window:length(1)
then
	retract($gamePlay);
	channels["outcomes"].send($playerId + " plays game");
	System.out.println("GamePlay["+$gamePlay+"] retracted");
end

