package it.redhat.hacep.playground.rules.reward.catalog;

import it.redhat.hacep.playground.rules.model.Gameplay;
import it.redhat.hacep.playground.rules.model.GameplayBet;

import accumulate it.redhat.hacep.playground.rules.reward.catalog.ConsecutiveDaysAccumulateFunction consecutivedays;

declare Gameplay
    @role( event )
    @timestamp( timestamp.getTime() )
    @expires( 60d )
end

declare GameplayBet
    @role( event )
    @timestamp ( timestamp.getTime() )
    @expires( 60d )
end

