package it.redhat.hacep.rules.reward.catalog;

import it.redhat.hacep.rules.model.Gameplay;

rule "When a user plays a game T times in D Days"
when
    $gamePlay : Gameplay($playerId : playerId) over window:length(1)
    $numberOfTimes : Number( intValue == 100)
    				 from accumulate ($gamePlayCount : Gameplay($gamePlay.playerId == playerId) over window:time( 30d ),
    				 count($gamePlayCount))
then
	channels["outcomes"].send($playerId + " plays game " + $numberOfTimes+ " times in 30 days");
	channels["audit"].send($gamePlay.getId() + " | COD_31 | " + $gamePlay.getPlayerId() + " | rule consequence.");
end

