import it.redhat.hacep.cluster.TestFact

dialect  "mvel"

global java.util.List list

declare TestFact
    @role( event )
    @timestamp ( instant.toEpochMilli() )
    @expires( 1d )
end

rule "proxy-rule"
    when
        $cumulative: Long(longValue>0) from accumulate(
            $g: Long() from entry-point DEFAULT,
            init(long total = 0),
            action(total += ($g * 2)),
            result(total)
        )
    then
        list.add($cumulative);
end
